export const MACHINE_STATES = {
  0: 'Power-on',
  1: 'Standby',
  2: 'AC Power (Bypass)',
  3: 'Inverter Operation',
  4: 'AC Power (Bypass)',
  5: 'Inverter Operation',
  6: 'Inverter to AC Power',
  7: 'Switching',
  8: 'Activating',
  9: 'Shutdown',
  10: 'Fault'
};

export const CHARGE_STATES = {
  0: 'Charge Off',
  1: 'Quick Charge',
  2: 'Const Voltage Charge',
  4: 'Float Charge',
  5: 'Reserved',
  6: 'Li Battery Activate',
  8: 'Full'
};

export const FAULT_CODES = {
  0: 'No Fault',
  1: 'Battery Under-Voltage',
  2: 'Battery Overcurrent (SW)',
  3: 'Disconnected Battery',
  4: 'Battery Over-Discharge',
  5: 'Battery Overcurrent (HW)',
  6: 'Battery Overvoltage',
  7: 'Bus Overvoltage (HW)',
  8: 'Bus Overvoltage (SW)',
  9: 'PV Overvoltage',
  10: 'Boost Overcurrent (SW)',
  11: 'Boost Overcurrent (HW)',
  12: 'SPI Communication Fault',
  13: 'Bypass Overload',
  14: 'Inverter Overload',
  15: 'AC Overcurrent (HW)',
  16: 'Slave Chip OFF Request',
  17: 'Inverter Short-Circuit',
  18: 'Bus Soft-Start Failure',
  19: 'PV Heat Sink Over-Temp',
  20: 'Inverter Heat Sink Over-Temp',
  21: 'Fan Fault',
  22: 'EEPROM Fault',
  23: 'Model Setting Error',
  24: 'Bus Voltage Imbalance',
  25: 'Bus Short-Circuit',
  26: 'AC Relay Short-Circuit',
  28: 'Mains Phase Error',
  29: 'Bus Low-Voltage',
  30: 'Battery Capacity <10%',
  31: 'Battery Capacity <5%',
  32: 'Battery Low Capacity OFF',
  34: 'CAN Communication Fault',
  35: 'Parallel Address Error',
  37: 'Parallel Current Sharing Fault',
  38: 'Parallel Battery Voltage Difference',
  39: 'Parallel AC Source Inconsistent',
  40: 'Parallel HW Sync Error',
  41: 'Inverter DC Voltage Error',
  42: 'Parallel FW Version Inconsistent',
  43: 'Parallel Connection Fault',
  44: 'Serial Number Error',
  45: 'Split-Phase Setting Error',
  56: 'Low Insulation Resistance',
  57: 'Leakage Current Overload',
  58: 'BMS Communication Error',
  60: 'BMS Under-Temperature',
  61: 'BMS Over-Temperature',
  62: 'BMS Overcurrent',
  63: 'BMS Under-Voltage',
  64: 'BMS Overvoltage'
};

export const REGISTERS = {
  PRODUCT_INFO: {
    MINOR_VERSION: { address: 0x000A, length: 1, scale: 1, type: 'uint16', unit: '' },
    MACH_TYPE: { address: 0x000B, length: 1, scale: 1, type: 'uint16', unit: '' },
    SOFTWARE_VERSION: { address: 0x0014, length: 2, scale: 1, type: 'uint16', unit: '' },
    HARDWARE_VERSION: { address: 0x0016, length: 2, scale: 1, type: 'uint16', unit: '' },
    RS485_ADDR: { address: 0x001A, length: 1, scale: 1, type: 'uint16', unit: '' },
  },

  DC_DATA: {
    BAT_SOC: { address: 0x0100, length: 1, scale: 1, type: 'uint16', unit: '%' },
    BAT_VOLT: { address: 0x0101, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    CHARGE_CURR: { address: 0x0102, length: 1, scale: 0.1, type: 'int16', unit: 'A' },
    DEVICE_BAT_TEMPER: { address: 0x0103, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    BAT_SOH: { address: 0x0104, length: 1, scale: 0.1, type: 'uint16', unit: '%' },
    BAT_RATED_CAPACITY: { address: 0x0105, length: 1, scale: 0.01, type: 'uint16', unit: 'Ah' },
    BAT_REMAIN_CAPACITY: { address: 0x0106, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    PV1_VOLT: { address: 0x0107, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    PV1_CURR: { address: 0x0108, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    PV1_CHARGE_POWER: { address: 0x0109, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    PV_TOTAL_POWER: { address: 0x010A, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    CHARGE_STATE: { address: 0x010B, length: 1, scale: 1, type: 'uint16', unit: '' },
    BATTERY_CYCLE_COUNT: { address: 0x010C, length: 1, scale: 2, type: 'uint16', unit: 'cycles' },
    CHARGE_POWER: { address: 0x010E, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    PV2_VOLT: { address: 0x010F, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    PV2_CURR: { address: 0x0110, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    PV2_CHARGE_POWER: { address: 0x0111, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    BAT_BMS_VOLT: { address: 0x0112, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    BAT_BMS_CURR: { address: 0x0113, length: 1, scale: 0.1, type: 'int16', unit: 'A' },
    BAT_BMS_TEMP: { address: 0x0114, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    BAT_BMS_CHG_LIMIT_VOLT: { address: 0x0115, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    BAT_BMS_CHG_LIMIT_CURR: { address: 0x0116, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    BAT_BMS_DCHG_LIMIT_CURR: { address: 0x0117, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    BMS_ALARM_H: { address: 0x0118, length: 1, scale: 1, type: 'uint16', unit: '' },
    BMS_ALARM_L: { address: 0x0119, length: 1, scale: 1, type: 'uint16', unit: '' },
    BMS_PROTECT_H: { address: 0x011A, length: 1, scale: 1, type: 'uint16', unit: '' },
    BMS_PROTECT_L: { address: 0x011B, length: 1, scale: 1, type: 'uint16', unit: '' },
  },

  INVERTER_DATA: {
    CURR_ERR_REG: { address: 0x0200, length: 4, scale: 1, type: 'uint16', unit: '' },
    CURR_FCODE: { address: 0x0204, length: 4, scale: 1, type: 'uint16', unit: '' },
    SYS_DATETIME: { address: 0x020C, length: 3, scale: 1, type: 'uint16', unit: '' },
    MACHINE_STATE: { address: 0x0210, length: 1, scale: 1, type: 'uint16', unit: '' },
    PRIORITY_FLAG: { address: 0x0211, length: 1, scale: 1, type: 'uint16', unit: '' },
    BUS_VOLT_SUM: { address: 0x0212, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_VOLT_A: { address: 0x0213, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_CURR_A: { address: 0x0214, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    GRID_FREQ: { address: 0x0215, length: 1, scale: 0.01, type: 'uint16', unit: 'Hz' },
    INV_VOLT_A: { address: 0x0216, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_CURR_A: { address: 0x0217, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    INV_FREQ: { address: 0x0218, length: 1, scale: 0.01, type: 'uint16', unit: 'Hz' },
    LOAD_CURR_A: { address: 0x0219, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_PF: { address: 0x021A, length: 1, scale: 0.01, type: 'int16', unit: '' },
    LOAD_ACTIVE_POWER_A: { address: 0x021B, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    LOAD_APPARENT_POWER_A: { address: 0x021C, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    LINE_CHG_CURR: { address: 0x021E, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_RATIO_A: { address: 0x021F, length: 1, scale: 1, type: 'uint16', unit: '%' },
    TEMPER_A: { address: 0x0220, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    TEMPER_B: { address: 0x0221, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    TEMPER_C: { address: 0x0222, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    TEMPER_D: { address: 0x0223, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    IBUCK1: { address: 0x0224, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    P_BUS_VOLT: { address: 0x0228, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    N_BUS_VOLT: { address: 0x0229, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_VOLT_B: { address: 0x022A, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_VOLT_C: { address: 0x022B, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_VOLT_B: { address: 0x022C, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_VOLT_C: { address: 0x022D, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_CURR_B: { address: 0x022E, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    INV_CURR_C: { address: 0x022F, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_CURR_B: { address: 0x0230, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_CURR_C: { address: 0x0231, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_ACTIVE_POWER_B: { address: 0x0232, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    LOAD_ACTIVE_POWER_C: { address: 0x0233, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    LOAD_REACTIVE_POWER_B: { address: 0x0234, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    LOAD_REACTIVE_POWER_C: { address: 0x0235, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    LOAD_RATIO_B: { address: 0x0236, length: 1, scale: 1, type: 'uint16', unit: '%' },
    LOAD_RATIO_C: { address: 0x0237, length: 1, scale: 1, type: 'uint16', unit: '%' },
    GRID_CURR_B: { address: 0x0238, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    GRID_CURR_C: { address: 0x0239, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    GRID_ACTIVE_POWER_A: { address: 0x023A, length: 1, scale: 1, type: 'int16', unit: 'W' },
    GRID_ACTIVE_POWER_B: { address: 0x023B, length: 1, scale: 1, type: 'int16', unit: 'W' },
    GRID_ACTIVE_POWER_C: { address: 0x023C, length: 1, scale: 1, type: 'int16', unit: 'W' },
    GRID_APPARENT_POWER_A: { address: 0x023D, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    GRID_APPARENT_POWER_B: { address: 0x023E, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    GRID_APPARENT_POWER_C: { address: 0x023F, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    HOME_LOAD_ACTIVE_POWER_A: { address: 0x0240, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    HOME_LOAD_ACTIVE_POWER_B: { address: 0x0241, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    HOME_LOAD_ACTIVE_POWER_C: { address: 0x0242, length: 1, scale: 1, type: 'uint16', unit: 'W' },
  },

  ENERGY_STATS: {
    GENERAT_ENERGY_TO_GRID_TODAY: { address: 0xF02C, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    BAT_CHG_AH_TODAY: { address: 0xF02D, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    BAT_DISCHG_AH_TODAY: { address: 0xF02E, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    GENERAT_ENERGY_TODAY: { address: 0xF02F, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    USED_ENERGY_TODAY: { address: 0xF030, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    WORK_DAYS_TOTAL: { address: 0xF031, length: 1, scale: 1, type: 'uint16', unit: 'days' },
    GRID_ENERGY_TOTAL: { address: 0xF032, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    BAT_CHG_AH_TOTAL: { address: 0xF034, length: 2, scale: 1, type: 'uint32', unit: 'Ah' },
    BAT_DISCHG_AH_TOTAL: { address: 0xF036, length: 2, scale: 1, type: 'uint32', unit: 'Ah' },
    GENERAT_ENERGY_TOTAL: { address: 0xF038, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    USED_ENERGY_TOTAL: { address: 0xF03A, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    LINE_CHG_ENERGY_TDAY: { address: 0xF03C, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    LOAD_CONSUM_LINE_TDAY: { address: 0xF03D, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    INV_WORK_TIME_TODAY: { address: 0xF03E, length: 1, scale: 1, type: 'uint16', unit: 'min' },
    LINE_WORK_TIME_TODAY: { address: 0xF03F, length: 1, scale: 1, type: 'uint16', unit: 'min' },
    LINE_CHG_ENERGY_TOTAL: { address: 0xF046, length: 2, scale: 1, type: 'uint32', unit: 'Ah' },
    LOAD_CONSUM_LINE_TOTAL: { address: 0xF048, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    INV_WORK_TIME_TOTAL: { address: 0xF04A, length: 1, scale: 1, type: 'uint16', unit: 'h' },
    LINE_WORK_TIME_TOTAL: { address: 0xF04B, length: 1, scale: 1, type: 'uint16', unit: 'h' },
    BAT_CHG_KWH_TODAY: { address: 0xF04D, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    BAT_DISCHG_KWH_TODAY: { address: 0xF04E, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    BAT_CHG_KWH_TOTAL: { address: 0xF04F, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    BAT_DISCHG_KWH_TOTAL: { address: 0xF051, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
  }
};

export const REGISTER_GROUPS = {
  SYSTEM_STATUS: [
    { name: 'MACHINE_STATE', address: 0x0210, count: 1 },
    { name: 'CURR_FCODE', address: 0x0204, count: 4 },
  ],
  
  BATTERY: [
    { name: 'BATTERY_BASIC_1', address: 0x0100, count: 8 },
    { name: 'BATTERY_BASIC_2', address: 0x0108, count: 7 },
    { name: 'BATTERY_BMS', address: 0x0112, count: 10 },
  ],
  
  AC_GRID_INV_LOAD: [
    { name: 'AC_DATA_BASIC_1', address: 0x0213, count: 8 },
    { name: 'AC_DATA_BASIC_2', address: 0x021B, count: 5 },
    { name: 'AC_DATA_TEMPS', address: 0x0220, count: 5 },
    { name: 'AC_DATA_PHASE_B', address: 0x022A, count: 8 },
    { name: 'AC_DATA_LOAD', address: 0x0232, count: 10 },
  ],
  
  ENERGY: [
    { name: 'ENERGY_TODAY', address: 0xF02C, count: 6 },
    { name: 'ENERGY_TOTALS_1', address: 0xF032, count: 10 },
    { name: 'ENERGY_TOTALS_2', address: 0xF03C, count: 4 },
    { name: 'ENERGY_TOTALS_3', address: 0xF046, count: 6 },
    { name: 'ENERGY_KWH_TODAY', address: 0xF04D, count: 2 },
    { name: 'ENERGY_KWH_TOTAL', address: 0xF04F, count: 4 },
  ]
};

// Configuration registers (R/W) grouped by category
export const CONFIG_REGISTERS = {
  OUTPUT: [
    { address: 0xE204, name: 'Output Priority', key: 'outputPriority', scale: 1, unit: '', min: 0, max: 2, description: '0:Solar 1:Grid 2:SBU (Solar-Battery-Utility)' },
    { address: 0xE208, name: 'Output Voltage', key: 'outputVolt', scale: 0.1, unit: 'V', min: 100, max: 264, description: 'AC output voltage setting' },
    { address: 0xE209, name: 'Output Frequency', key: 'outputFreq', scale: 0.01, unit: 'Hz', min: 45, max: 65, description: 'AC output frequency (50Hz or 60Hz)' },
    { address: 0xE20B, name: 'AC Voltage Range', key: 'acVoltRange', scale: 1, unit: '', min: 0, max: 1, description: '0:Wide band (APL) 1:Narrow band (UPS)' },
    { address: 0xE20C, name: 'Power Saving Mode', key: 'powerSaving', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE20D, name: 'Auto Restart on Overload', key: 'autoRestartOL', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE20E, name: 'Auto Restart on Over-temp', key: 'autoRestartOT', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE210, name: 'Audible Alarm', key: 'alarmEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE212, name: 'Bypass on Overload', key: 'bypOnOL', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
  ],
  
  BATTERY: [
    { address: 0xE002, name: 'Battery Capacity', key: 'batCap', scale: 1, unit: 'Ah', min: 0, max: 400, description: 'Battery rated capacity' },
    { address: 0xE003, name: 'Battery Voltage', key: 'batVoltage', scale: 1, unit: 'V', min: 12, max: 96, description: '12/24/36/48V system voltage' },
    { address: 0xE004, name: 'Battery Type', key: 'batType', scale: 1, unit: '', min: 0, max: 14, description: '0:User 1:SLD 2:FLD 3:GEL 4-6:LiFePO4' },
    { address: 0xE005, name: 'Over Voltage Protection', key: 'batOverVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Over-voltage protection (12V basis)' },
    { address: 0xE006, name: 'Charge Limit Voltage', key: 'chgLimitVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Charge cutoff voltage (12V basis)' },
    { address: 0xE007, name: 'Equalize Charge Voltage', key: 'equalizVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Equalization voltage (12V basis)' },
    { address: 0xE009, name: 'Float Charge Voltage', key: 'floatVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Float charge voltage (12V basis)' },
    { address: 0xE00C, name: 'Under Voltage Alarm', key: 'underVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Low voltage alarm (12V basis)' },
    { address: 0xE00D, name: 'Over-discharge Voltage', key: 'overDischgVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Load cutoff voltage (12V basis)' },
    { address: 0xE00F, name: 'Discharge Cutoff SoC', key: 'stopSoc', scale: 1, unit: '%', min: 0, max: 100, description: 'Minimum SoC before load cutoff' },
    { address: 0xE021, name: 'Max Discharge Current', key: 'maxDischgCurr', scale: 1, unit: 'A', min: 0, max: 200, description: 'Maximum battery discharge current' },
  ],
  
  CHARGING: [
    { address: 0xE001, name: 'PV Charge Current', key: 'pvChgCurr', scale: 0.1, unit: 'A', min: 0, max: 150, description: 'PV charging current limit' },
    { address: 0xE20A, name: 'Max Total Charge Current', key: 'maxChgCurr', scale: 0.1, unit: 'A', min: 0, max: 200, description: 'Total maximum charging current' },
    { address: 0xE205, name: 'AC Charge Current Limit', key: 'acChgLimit', scale: 0.1, unit: 'A', min: 0, max: 200, description: 'Max current from AC/grid charging' },
    { address: 0xE20F, name: 'Charge Source Priority', key: 'chgSourcePriority', scale: 1, unit: '', min: 0, max: 3, description: '0:PV first 1:AC first 2:Hybrid 3:PV only' },
    { address: 0xE011, name: 'Equalize Charge Time', key: 'equalizTime', scale: 1, unit: 'min', min: 0, max: 900, description: 'Equalization charge duration' },
    { address: 0xE012, name: 'Boost Charge Time', key: 'boostTime', scale: 1, unit: 'min', min: 10, max: 900, description: 'Boost charge duration' },
    { address: 0xE206, name: 'Battery Equalize Enable', key: 'equalizEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
  ],
  
  SOLAR: [
    { address: 0xE039, name: 'PV Power Priority', key: 'pvPriority', scale: 1, unit: '', min: 0, max: 2, description: '0:Charge priority 1:Load priority' },
  ],
  
  TIMING: [
    { address: 0xE02C, name: 'Timed Charge Enable', key: 'timedChgEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE026, name: 'Charge Start Time 1', key: 'chgStart1', scale: 1, unit: '', min: 0, max: 5947, description: 'HH*256+MM (e.g., 8:00 = 2048)' },
    { address: 0xE027, name: 'Charge End Time 1', key: 'chgEnd1', scale: 1, unit: '', min: 0, max: 5947, description: 'HH*256+MM' },
    { address: 0xE033, name: 'Timed Discharge Enable', key: 'timedDischgEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE02D, name: 'Discharge Start Time 1', key: 'dischgStart1', scale: 1, unit: '', min: 0, max: 5947, description: 'HH*256+MM' },
    { address: 0xE02E, name: 'Discharge End Time 1', key: 'dischgEnd1', scale: 1, unit: '', min: 0, max: 5947, description: 'HH*256+MM' },
  ],
  
  GRID: [
    { address: 0xE037, name: 'Grid Mode', key: 'gridMode', scale: 1, unit: '', min: 0, max: 3, description: '0:Off-grid 1:Grid-tied 2:ACout anti-backfeed' },
    { address: 0xE038, name: 'Leakage Detection', key: 'leakageDetect', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
  ]
};
  OUTPUT: [
    { address: 0xE204, name: 'Output Priority', key: 'outputPriority', scale: 1, unit: '', min: 0, max: 2, description: '0:Solar 1:Grid 2:SBU (Solar-Battery-Utility)' },
    { address: 0xE208, name: 'Output Voltage', key: 'outputVolt', scale: 0.1, unit: 'V', min: 100, max: 264, description: 'AC output voltage setting' },
    { address: 0xE209, name: 'Output Frequency', key: 'outputFreq', scale: 0.01, unit: 'Hz', min: 45, max: 65, description: 'AC output frequency (50Hz or 60Hz)' },
    { address: 0xE20B, name: 'AC Voltage Range', key: 'acVoltRange', scale: 1, unit: '', min: 0, max: 1, description: '0:Wide band (APL) 1:Narrow band (UPS)' },
    { address: 0xE20C, name: 'Power Saving Mode', key: 'powerSaving', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE20D, name: 'Auto Restart on Overload', key: 'autoRestartOL', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE20E, name: 'Auto Restart on Over-temp', key: 'autoRestartOT', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE210, name: 'Alarm Enable', key: 'alarmEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled (audible alarm)' },
    { address: 0xE212, name: 'Bypass on Overload', key: 'bypOnOL', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
  ],
  
  BATTERY: [
    { address: 0xE002, name: 'Battery Capacity', key: 'batCap', scale: 1, unit: 'Ah', min: 0, max: 400, description: 'Battery rated capacity (Ah)' },
    { address: 0xE003, name: 'Battery Voltage', key: 'batVoltage', scale: 1, unit: 'V', min: 12, max: 96, description: '12V/24V/36V/48V system voltage' },
    { address: 0xE004, name: 'Battery Type', key: 'batType', scale: 1, unit: '', min: 0, max: 14, description: '0:User 1:SLD 2:FLD 3:GEL 4-6:LiFePO4' },
    { address: 0xE005, name: 'Over Voltage Protection', key: 'batOverVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Battery over-voltage protection (12V basis)' },
    { address: 0xE006, name: 'Charge Limit Voltage', key: 'chgLimitVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Charge cutoff voltage (12V basis)' },
    { address: 0xE007, name: 'Equalize Charge Voltage', key: 'equalizVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Equalization voltage (12V basis)' },
    { address: 0xE009, name: 'Float Charge Voltage', key: 'floatVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Float charge voltage (12V basis)' },
    { address: 0xE00C, name: 'Under Voltage Alarm', key: 'underVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Low voltage alarm (12V basis)' },
    { address: 0xE00D, name: 'Over-discharge Voltage', key: 'overDischgVolt', scale: 0.1, unit: 'V', min: 9, max: 15.5, description: 'Load cutoff voltage (12V basis)' },
    { address: 0xE00F, name: 'Discharge Cutoff SoC', key: 'stopSoc', scale: 1, unit: '%', min: 0, max: 100, description: 'Minimum SoC before load cutoff' },
    { address: 0xE021, name: 'Max Discharge Current', key: 'maxDischgCurr', scale: 1, unit: 'A', min: 0, max: 200, description: 'Maximum battery discharge current' },
  ],
  
  CHARGING: [
    { address: 0xE001, name: 'PV Charge Current', key: 'pvChgCurr', scale: 0.1, unit: 'A', min: 0, max: 150, description: 'PV charging current limit' },
    { address: 0xE20A, name: 'Max Total Charge Current', key: 'maxChgCurr', scale: 0.1, unit: 'A', min: 0, max: 200, description: 'Total maximum charging current' },
    { address: 0xE205, name: 'AC Charge Current Limit', key: 'acChgLimit', scale: 0.1, unit: 'A', min: 0, max: 200, description: 'Max current from AC/grid charging' },
    { address: 0xE20F, name: 'Charge Source Priority', key: 'chgSourcePriority', scale: 1, unit: '', min: 0, max: 3, description: '0:PV first 1:AC first 2:Hybrid 3:PV only' },
    { address: 0xE011, name: 'Equalize Charge Time', key: 'equalizTime', scale: 1, unit: 'min', min: 0, max: 900, description: 'Equalization charge duration' },
    { address: 0xE012, name: 'Boost Charge Time', key: 'boostTime', scale: 1, unit: 'min', min: 10, max: 900, description: 'Boost charge duration' },
  ],
  
  SOLAR: [
    { address: 0xE039, name: 'PV Power Priority', key: 'pvPriority', scale: 1, unit: '', min: 0, max: 2, description: '0:Charge priority 1:Load priority' },
  ],
  
  TIMING: [
    { address: 0xE02C, name: 'Timed Charge Enable', key: 'timedChgEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE026, name: 'Charge Start Time 1', key: 'chgStart1', scale: 1, unit: 'HH:MM', min: 0, max: 5947, description: 'Format: HH*256+MM (e.g., 8:00 = 2048)' },
    { address: 0xE027, name: 'Charge End Time 1', key: 'chgEnd1', scale: 1, unit: 'HH:MM', min: 0, max: 5947, description: 'Format: HH*256+MM' },
    { address: 0xE033, name: 'Timed Discharge Enable', key: 'timedDischgEn', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
    { address: 0xE02D, name: 'Discharge Start Time 1', key: 'dischgStart1', scale: 1, unit: 'HH:MM', min: 0, max: 5947, description: 'Format: HH*256+MM' },
    { address: 0xE02E, name: 'Discharge End Time 1', key: 'dischgEnd1', scale: 1, unit: 'HH:MM', min: 0, max: 5947, description: 'Format: HH*256+MM' },
  ],
  
  GRID: [
    { address: 0xE037, name: 'Grid Mode', key: 'gridMode', scale: 1, unit: '', min: 0, max: 3, description: '0:Off-grid 1:Grid-tied 2:ACout anti-backfeed 3:ACin anti-backfeed' },
    { address: 0xE038, name: 'Leakage Detection', key: 'leakageDetect', scale: 1, unit: '', min: 0, max: 1, description: '0:Disabled 1:Enabled' },
  ]
};
