export const MACHINE_STATES = {
  0: 'Power-on Delay',
  1: 'Standby',
  2: 'Initialization',
  3: 'Soft Start',
  4: 'AC Power Operation (Bypass)',
  5: 'Inverter Operation',
  6: 'Inverter to AC Power',
  7: 'AC Power to Inverter',
  8: 'Battery Activation',
  9: 'Manual Shutdown',
  10: 'Fault'
};

export const CHARGE_STATES = {
  0: 'Charge Off',
  1: 'Quick Charge',
  2: 'Const Voltage Charge',
  4: 'Float Charge',
  5: 'Reserved',
  6: 'Li Battery Activate',
  8: 'Full'
};

export const REGISTERS = {
  PRODUCT_INFO: {
    MINOR_VERSION: { address: 0x000A, length: 1, scale: 1, type: 'uint16', unit: '' },
    MACH_TYPE: { address: 0x000B, length: 1, scale: 1, type: 'uint16', unit: '' },
    SOFTWARE_VERSION: { address: 0x0014, length: 2, scale: 1, type: 'uint16', unit: '' },
    HARDWARE_VERSION: { address: 0x0016, length: 2, scale: 1, type: 'uint16', unit: '' },
    RS485_ADDR: { address: 0x001A, length: 1, scale: 1, type: 'uint16', unit: '' },
  },

  DC_DATA: {
    BAT_SOC: { address: 0x0100, length: 1, scale: 1, type: 'uint16', unit: '%' },
    BAT_VOLT: { address: 0x0101, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    CHARGE_CURR: { address: 0x0102, length: 1, scale: 0.1, type: 'int16', unit: 'A' },
    DEVICE_BAT_TEMPER: { address: 0x0103, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    BAT_SOH: { address: 0x0104, length: 1, scale: 0.1, type: 'uint16', unit: '%' },
    BAT_RATED_CAPACITY: { address: 0x0105, length: 1, scale: 0.01, type: 'uint16', unit: 'Ah' },
    BAT_REMAIN_CAPACITY: { address: 0x0106, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    PV1_VOLT: { address: 0x0107, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    PV1_CURR: { address: 0x0108, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    PV1_CHARGE_POWER: { address: 0x0109, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    PV_TOTAL_POWER: { address: 0x010A, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    CHARGE_STATE: { address: 0x010B, length: 1, scale: 1, type: 'uint16', unit: '' },
    BATTERY_CYCLE_COUNT: { address: 0x010C, length: 1, scale: 2, type: 'uint16', unit: 'cycles' },
    CHARGE_POWER: { address: 0x010E, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    PV2_VOLT: { address: 0x010F, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    PV2_CURR: { address: 0x0110, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    PV2_CHARGE_POWER: { address: 0x0111, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    BAT_BMS_VOLT: { address: 0x0112, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    BAT_BMS_CURR: { address: 0x0113, length: 1, scale: 0.1, type: 'int16', unit: 'A' },
    BAT_BMS_TEMP: { address: 0x0114, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    BAT_BMS_CHG_LIMIT_VOLT: { address: 0x0115, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    BAT_BMS_CHG_LIMIT_CURR: { address: 0x0116, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    BAT_BMS_DCHG_LIMIT_CURR: { address: 0x0117, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    BMS_ALARM_H: { address: 0x0118, length: 1, scale: 1, type: 'uint16', unit: '' },
    BMS_ALARM_L: { address: 0x0119, length: 1, scale: 1, type: 'uint16', unit: '' },
    BMS_PROTECT_H: { address: 0x011A, length: 1, scale: 1, type: 'uint16', unit: '' },
    BMS_PROTECT_L: { address: 0x011B, length: 1, scale: 1, type: 'uint16', unit: '' },
  },

  INVERTER_DATA: {
    CURR_ERR_REG: { address: 0x0200, length: 4, scale: 1, type: 'uint16', unit: '' },
    CURR_FCODE: { address: 0x0204, length: 4, scale: 1, type: 'uint16', unit: '' },
    SYS_DATETIME: { address: 0x020C, length: 3, scale: 1, type: 'uint16', unit: '' },
    MACHINE_STATE: { address: 0x0210, length: 1, scale: 1, type: 'uint16', unit: '' },
    PRIORITY_FLAG: { address: 0x0211, length: 1, scale: 1, type: 'uint16', unit: '' },
    BUS_VOLT_SUM: { address: 0x0212, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_VOLT_A: { address: 0x0213, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_CURR_A: { address: 0x0214, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    GRID_FREQ: { address: 0x0215, length: 1, scale: 0.01, type: 'uint16', unit: 'Hz' },
    INV_VOLT_A: { address: 0x0216, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_CURR_A: { address: 0x0217, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    INV_FREQ: { address: 0x0218, length: 1, scale: 0.01, type: 'uint16', unit: 'Hz' },
    LOAD_CURR_A: { address: 0x0219, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_PF: { address: 0x021A, length: 1, scale: 0.01, type: 'int16', unit: '' },
    LOAD_ACTIVE_POWER_A: { address: 0x021B, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    LOAD_APPARENT_POWER_A: { address: 0x021C, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    LINE_CHG_CURR: { address: 0x021E, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_RATIO_A: { address: 0x021F, length: 1, scale: 1, type: 'uint16', unit: '%' },
    TEMPER_A: { address: 0x0220, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    TEMPER_B: { address: 0x0221, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    TEMPER_C: { address: 0x0222, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    TEMPER_D: { address: 0x0223, length: 1, scale: 0.1, type: 'int16', unit: '°C' },
    IBUCK1: { address: 0x0224, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    P_BUS_VOLT: { address: 0x0228, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    N_BUS_VOLT: { address: 0x0229, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_VOLT_B: { address: 0x022A, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    GRID_VOLT_C: { address: 0x022B, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_VOLT_B: { address: 0x022C, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_VOLT_C: { address: 0x022D, length: 1, scale: 0.1, type: 'uint16', unit: 'V' },
    INV_CURR_B: { address: 0x022E, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    INV_CURR_C: { address: 0x022F, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_CURR_B: { address: 0x0230, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_CURR_C: { address: 0x0231, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    LOAD_ACTIVE_POWER_B: { address: 0x0232, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    LOAD_ACTIVE_POWER_C: { address: 0x0233, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    LOAD_REACTIVE_POWER_B: { address: 0x0234, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    LOAD_REACTIVE_POWER_C: { address: 0x0235, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    LOAD_RATIO_B: { address: 0x0236, length: 1, scale: 1, type: 'uint16', unit: '%' },
    LOAD_RATIO_C: { address: 0x0237, length: 1, scale: 1, type: 'uint16', unit: '%' },
    GRID_CURR_B: { address: 0x0238, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    GRID_CURR_C: { address: 0x0239, length: 1, scale: 0.1, type: 'uint16', unit: 'A' },
    GRID_ACTIVE_POWER_A: { address: 0x023A, length: 1, scale: 1, type: 'int16', unit: 'W' },
    GRID_ACTIVE_POWER_B: { address: 0x023B, length: 1, scale: 1, type: 'int16', unit: 'W' },
    GRID_ACTIVE_POWER_C: { address: 0x023C, length: 1, scale: 1, type: 'int16', unit: 'W' },
    GRID_APPARENT_POWER_A: { address: 0x023D, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    GRID_APPARENT_POWER_B: { address: 0x023E, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    GRID_APPARENT_POWER_C: { address: 0x023F, length: 1, scale: 1, type: 'uint16', unit: 'VA' },
    HOME_LOAD_ACTIVE_POWER_A: { address: 0x0240, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    HOME_LOAD_ACTIVE_POWER_B: { address: 0x0241, length: 1, scale: 1, type: 'uint16', unit: 'W' },
    HOME_LOAD_ACTIVE_POWER_C: { address: 0x0242, length: 1, scale: 1, type: 'uint16', unit: 'W' },
  },

  ENERGY_STATS: {
    GENERAT_ENERGY_TO_GRID_TODAY: { address: 0xF02C, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    BAT_CHG_AH_TODAY: { address: 0xF02D, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    BAT_DISCHG_AH_TODAY: { address: 0xF02E, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    GENERAT_ENERGY_TODAY: { address: 0xF02F, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    USED_ENERGY_TODAY: { address: 0xF030, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    WORK_DAYS_TOTAL: { address: 0xF031, length: 1, scale: 1, type: 'uint16', unit: 'days' },
    GRID_ENERGY_TOTAL: { address: 0xF032, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    BAT_CHG_AH_TOTAL: { address: 0xF034, length: 2, scale: 1, type: 'uint32', unit: 'Ah' },
    BAT_DISCHG_AH_TOTAL: { address: 0xF036, length: 2, scale: 1, type: 'uint32', unit: 'Ah' },
    GENERAT_ENERGY_TOTAL: { address: 0xF038, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    USED_ENERGY_TOTAL: { address: 0xF03A, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    LINE_CHG_ENERGY_TDAY: { address: 0xF03C, length: 1, scale: 1, type: 'uint16', unit: 'Ah' },
    LOAD_CONSUM_LINE_TDAY: { address: 0xF03D, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    INV_WORK_TIME_TODAY: { address: 0xF03E, length: 1, scale: 1, type: 'uint16', unit: 'min' },
    LINE_WORK_TIME_TODAY: { address: 0xF03F, length: 1, scale: 1, type: 'uint16', unit: 'min' },
    LINE_CHG_ENERGY_TOTAL: { address: 0xF046, length: 2, scale: 1, type: 'uint32', unit: 'Ah' },
    LOAD_CONSUM_LINE_TOTAL: { address: 0xF048, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    INV_WORK_TIME_TOTAL: { address: 0xF04A, length: 1, scale: 1, type: 'uint16', unit: 'h' },
    LINE_WORK_TIME_TOTAL: { address: 0xF04B, length: 1, scale: 1, type: 'uint16', unit: 'h' },
    BAT_CHG_KWH_TODAY: { address: 0xF04D, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    BAT_DISCHG_KWH_TODAY: { address: 0xF04E, length: 1, scale: 0.1, type: 'uint16', unit: 'kWh' },
    BAT_CHG_KWH_TOTAL: { address: 0xF04F, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
    BAT_DISCHG_KWH_TOTAL: { address: 0xF051, length: 2, scale: 0.1, type: 'uint32', unit: 'kWh' },
  }
};

export const REGISTER_GROUPS = {
  SYSTEM_STATUS: [
    { name: 'MACHINE_STATE', address: 0x0210, count: 1 },
    { name: 'CURR_FCODE', address: 0x0204, count: 4 },
  ],
  
  BATTERY: [
    { name: 'BATTERY_DATA', address: 0x0100, count: 28 },
  ],
  
  AC_GRID_INV_LOAD: [
    { name: 'AC_DATA_1', address: 0x0213, count: 32 },
    { name: 'AC_DATA_2', address: 0x0233, count: 19 },
  ],
  
  ENERGY: [
    { name: 'ENERGY_TODAY', address: 0xF02C, count: 6 },
    { name: 'ENERGY_TOTALS_1', address: 0xF032, count: 10 },
    { name: 'ENERGY_TOTALS_2', address: 0xF03C, count: 5 },
    { name: 'ENERGY_TOTALS_3', address: 0xF046, count: 6 },
    { name: 'ENERGY_KWH_TODAY', address: 0xF04D, count: 2 },
    { name: 'ENERGY_KWH_TOTAL', address: 0xF04F, count: 4 },
  ]
};
